### PR TITLE
add draw score

### PR DESCRIPTION
**Pull request by Kibadda**

### CODE REVIEW

**Review by alanfortlink — CHANGES_REQUESTED** [review]
Hey, I appreciate the PR. I only have one comment. If the player already has a file with their scores, when you read it, you'll have `M.scores.draw_score == nil`.

Can you add the following to the `match.lua`'s `read_scores` function? At the end of it:

```lua
if M.scores.draw_score == nil then
  M.scores.draw_score = 0
end
```

**Comment by Kibadda** [comment]
Oh yeah you are right. Forgot about that.

I'm on vacation right now till friday. Will update this pr as soon as I can.

**Comment by Kibadda** [comment]
Ok I added it.

**Review by alanfortlink — APPROVED** [review]
Thank you very much! I've been using this for a while and I get a draw more often than I realized. Great addition!

**Pull request merged**
